services:
#  redis:
#    image: redis
#    restart: on-failure
#    expose:
#      - 6379
#    env_file:
#      - ".env"

  db:
    image: postgres:18.6
    command:
      - '-p 5433'
    ports:
      - "5433:5433"
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p5433 -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 20s
      retries: 3
    env_file: 
      - ".env"

  api:
    image: streaming-api
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    environment:
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy
        restart: true

  receiver:
    image: streaming-api
    build: .
    command: uvicorn receiver.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - ".env"
    environment:
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy
        restart: true

volumes:
  postgres-data: