services:
#  redis:
#    image: redis
#    restart: on-failure
#    expose:
#      - 6379
#    env_file:
#      - ".env"

  db:
    image: postgres:18.6
    command:
      - '-p 5433'
    ports:
      - "5433:5433"
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p5433 -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 20s
      retries: 3
    env_file: 
      - ".env"

  kafka:
    image: apache/kafka:4.3.1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    volumes:
      - kafka-data:/var/lib/kafka/data

  api:
    image: streaming-api
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
#    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --workers 4
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    environment:
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy
        restart: true

  receiver:
    image: streaming-api
    build: .
#    command: uvicorn receiver.main:app --host 0.0.0.0 --port 8000 --reload
#    command: uvicorn receiver.main:app --host 0.0.0.0 --port 8000 --workers 8 --no-access-log
    command: uvicorn receiver.main:app --host 0.0.0.0 --port 8000 --workers 8 --no-access-log
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - ".env"
    environment:
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy
        restart: true

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - API_PROXY_TARGET=http://api:8000
    depends_on:
      - api

volumes:
  kafka-data:
  postgres-data:
  frontend-node-modules: