"""empty message

Revision ID: 8af6173104c0
Revises: a1f4c7b92e53
Create Date: 2026-09-30 12:36:44.340794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8af6173104c0'
down_revision: Union[str, Sequence[str], None] = 'a1f4c7b92e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('co', 'co2', 'methane', 'smoke', 'temperature', 'radiation', name='device_type').create(op.get_bind())
    op.create_table('devices',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('type', postgresql.ENUM('co', 'co2', 'methane', 'smoke', 'temperature', 'radiation', name='device_type', create_type=False), nullable=False),
    sa.Column('building_uuid', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_uuid'], ['buildings.uuid'], name=op.f('fk_devices_building_uuid_buildings')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_devices'))
    )
    op.create_index(op.f('ix_devices_building_uuid'), 'devices', ['building_uuid'], unique=False)
    op.create_index(op.f('ix_devices_key_hash'), 'devices', ['key_hash'], unique=True)
    op.create_index(op.f('ix_devices_name'), 'devices', ['name'], unique=False)
    op.create_index(op.f('ix_devices_serial_number'), 'devices', ['serial_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_serial_number'), table_name='devices')
    op.drop_index(op.f('ix_devices_name'), table_name='devices')
    op.drop_index(op.f('ix_devices_key_hash'), table_name='devices')
    op.drop_index(op.f('ix_devices_building_uuid'), table_name='devices')
    op.drop_table('devices')
    sa.Enum('co', 'co2', 'methane', 'smoke', 'temperature', 'radiation', name='device_type').drop(op.get_bind())
    # ### end Alembic commands ###
