"""empty message

Revision ID: 1584e527bc3a
Revises: f984f5d7baf2
Create Date: 2026-10-10 14:15:49.571040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1584e527bc3a'
down_revision: Union[str, Sequence[str], None] = 'f984f5d7baf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('level_1', 'level_2', 'level_3', 'level_4', name='alert_level').create(op.get_bind())
    op.create_table('default_thresholds',
    sa.Column('device_type', postgresql.ENUM('co', 'co2', 'methane', 'smoke', 'temperature', 'radiation', name='device_type', create_type=False), nullable=False),
    sa.Column('level', postgresql.ENUM('level_1', 'level_2', 'level_3', 'level_4', name='alert_level', create_type=False), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_default_thresholds')),
    sa.UniqueConstraint('device_type', 'level', name=op.f('uq_default_thresholds_device_type'))
    )
    op.create_table('device_thresholds',
    sa.Column('device_uuid', sa.UUID(), nullable=False),
    sa.Column('level', postgresql.ENUM('level_1', 'level_2', 'level_3', 'level_4', name='alert_level', create_type=False), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_uuid'], ['devices.uuid'], name=op.f('fk_device_thresholds_device_uuid_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_device_thresholds')),
    sa.UniqueConstraint('device_uuid', 'level', name=op.f('uq_device_thresholds_device_uuid'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_thresholds')
    op.drop_table('default_thresholds')
    sa.Enum('level_1', 'level_2', 'level_3', 'level_4', name='alert_level').drop(op.get_bind())
    # ### end Alembic commands ###
