"""empty message

Revision ID: d786836f6b40
Revises: 2cb3bb30e07e
Create Date: 2026-09-20 16:30:47.980946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd786836f6b40'
down_revision: Union[str, Sequence[str], None] = '2cb3bb30e07e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('buildings',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('company_uuid', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_uuid'], ['companies.uuid'], name=op.f('fk_buildings_company_uuid_companies')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_buildings'))
    )
    op.create_index(op.f('ix_buildings_company_uuid'), 'buildings', ['company_uuid'], unique=False)
    op.create_index(op.f('ix_buildings_name'), 'buildings', ['name'], unique=False)
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('building_uuid', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_building_uuid'), 'users', ['building_uuid'], unique=False)
    op.create_foreign_key(op.f('fk_users_building_uuid_buildings'), 'users', 'buildings', ['building_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_building_uuid_buildings'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_building_uuid'), table_name='users')
    op.drop_column('users', 'building_uuid')
    op.drop_column('users', 'is_superuser')
    op.drop_index(op.f('ix_buildings_name'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_company_uuid'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
