"""empty message

Revision ID: f984f5d7baf2
Revises: e7b2d4f09a61
Create Date: 2026-10-10 13:53:31.505162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f984f5d7baf2'
down_revision: Union[str, Sequence[str], None] = 'e7b2d4f09a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readings_device_uuid'), table_name='readings')
    op.drop_table('readings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readings',
    sa.Column('device_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('value', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_uuid'], ['devices.uuid'], name=op.f('fk_readings_device_uuid_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_readings'))
    )
    op.create_index(op.f('ix_readings_device_uuid'), 'readings', ['device_uuid'], unique=False)
    # ### end Alembic commands ###
