"""empty message

Revision ID: 98f1d2a41cd4
Revises: e7b2d4f09a61
Create Date: 2026-10-08 18:54:55.781301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f1d2a41cd4'
down_revision: Union[str, Sequence[str], None] = 'e7b2d4f09a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_buildings_company_uuid_companies'), 'buildings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_buildings_company_uuid_companies'), 'buildings', 'companies', ['company_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_devices_building_uuid_buildings'), 'devices', type_='foreignkey')
    op.create_foreign_key(op.f('fk_devices_building_uuid_buildings'), 'devices', 'buildings', ['building_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_users_building_uuid_buildings'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('fk_users_company_uuid_companies'), 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_building_uuid_buildings'), 'users', 'buildings', ['building_uuid'], ['uuid'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_users_company_uuid_companies'), 'users', 'companies', ['company_uuid'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_company_uuid_companies'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('fk_users_building_uuid_buildings'), 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_company_uuid_companies'), 'users', 'companies', ['company_uuid'], ['uuid'])
    op.create_foreign_key(op.f('fk_users_building_uuid_buildings'), 'users', 'buildings', ['building_uuid'], ['uuid'])
    op.drop_constraint(op.f('fk_devices_building_uuid_buildings'), 'devices', type_='foreignkey')
    op.create_foreign_key(op.f('fk_devices_building_uuid_buildings'), 'devices', 'buildings', ['building_uuid'], ['uuid'])
    op.drop_constraint(op.f('fk_buildings_company_uuid_companies'), 'buildings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_buildings_company_uuid_companies'), 'buildings', 'companies', ['company_uuid'], ['uuid'])
    # ### end Alembic commands ###
